// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI-V1VSZC3y8FV_feNdg0teEc2PQ-XZM0',
    appId: '1:641705878587:web:0b1a1bf658c403790d281e',
    messagingSenderId: '641705878587',
    projectId: 'my-project-a83df',
    authDomain: 'my-project-a83df.firebaseapp.com',
    storageBucket: 'my-project-a83df.firebasestorage.app',
    measurementId: 'G-YFR5QV0NGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpHK-j5cZbMjIWL_8rmW4hoC-Rz0ft9wY',
    appId: '1:641705878587:android:751fa924d00efa380d281e',
    messagingSenderId: '641705878587',
    projectId: 'my-project-a83df',
    storageBucket: 'my-project-a83df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbIQYZlY_lPwWUVAMawdk8aFo6FZpAXbc',
    appId: '1:641705878587:ios:08bd36b694af009e0d281e',
    messagingSenderId: '641705878587',
    projectId: 'my-project-a83df',
    storageBucket: 'my-project-a83df.firebasestorage.app',
    iosBundleId: 'com.example.firebaseConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbIQYZlY_lPwWUVAMawdk8aFo6FZpAXbc',
    appId: '1:641705878587:ios:08bd36b694af009e0d281e',
    messagingSenderId: '641705878587',
    projectId: 'my-project-a83df',
    storageBucket: 'my-project-a83df.firebasestorage.app',
    iosBundleId: 'com.example.firebaseConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI-V1VSZC3y8FV_feNdg0teEc2PQ-XZM0',
    appId: '1:641705878587:web:d1dd429f3f7e53a10d281e',
    messagingSenderId: '641705878587',
    projectId: 'my-project-a83df',
    authDomain: 'my-project-a83df.firebaseapp.com',
    storageBucket: 'my-project-a83df.firebasestorage.app',
    measurementId: 'G-E2R79CD4EQ',
  );
}
